// This file is generated by Sapper — do not edit it!
export const routes = [
	{ error: '4xx', load: () => import(/* webpackChunkName: "_4xx" */ '../../routes/4xx.html') },
	{ error: '5xx', load: () => import(/* webpackChunkName: "_5xx" */ '../../routes/5xx.html') },
	{ pattern: /^\/en\/blog\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "en_blog" */ '../../routes/en/blog/index.html') },
	{ pattern: /^\/en\/blog(?:\/([^\/]+))?\/?$/, params: match => ({ slug: match[1] }), load: () => import(/* webpackChunkName: "en_blog_$slug$" */ '../../routes/en/blog/[slug].html') },
	{ pattern: /^(?:\/([^\/]+))?\/?$/, params: match => ({ language: match[1] }), load: () => import(/* webpackChunkName: "$language$" */ '../../routes/[language]/index.html') },
	{ pattern: /^\/([^\/]+)\/contact\/?$/, params: match => ({ language: match[1] }), load: () => import(/* webpackChunkName: "$language$_contact" */ '../../routes/[language]/contact.html') },
	{ pattern: /^\/([^\/]+)\/portfolio\/?$/, params: match => ({ language: match[1] }), load: () => import(/* webpackChunkName: "$language$_portfolio" */ '../../routes/[language]/portfolio/index.html') },
	{ pattern: /^\/([^\/]+)\/team\/?$/, params: match => ({ language: match[1] }), load: () => import(/* webpackChunkName: "$language$_team" */ '../../routes/[language]/team.html') },
	{ pattern: /^\/([^\/]+)\/portfolio(?:\/([^\/]+))?\/?$/, params: match => ({ language: match[1], slug: match[2] }), load: () => import(/* webpackChunkName: "$language$_portfolio_$slug$" */ '../../routes/[language]/portfolio/[slug].html') }
];

if (module.hot) {
	import('/Users/jasper/Localhost/repositories/jbmoelker/voorhoede-colibri/node_modules/sapper/hmr-client.js').then(client => {
		client.connect(10000);
	});
}